spring:
  datasource:
    username: bemobi
    password: 123qwe
    url: jdbc:postgresql://localhost:5432/hackpucdb
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  context-path: /walletapi
  port: 8081

application:
  pay:
    host: http://localhost:8080/
