spring:
  datasource:
    username: bemobi
    password: 123qwe
    url: jdbc:postgresql://174.138.34.125:5432/hackpucdb
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  context-path: /walletapi
  port: 8081

application:
  pay:
    host: http://174.138.34.125:8080/
